### ISSUE TITLE
Wrap-up task

### ISSUE THREAD

**Issue by prigoyal** [MLH-Fellowship/vissl#17]
As the fellowship comes to end, we have following steps to do to wrap up:

- [x] Iterate and merge the PR #15  (Wednesday April, 7)
- [x] Send the isort , pre-commit related changes in [one pull request](https://github.com/facebookresearch/vissl/pull/283)
- [x] By end of April 12 stage https://github.com/MLH-Fellowship/vissl/pull/19 on top of https://github.com/facebookresearch/vissl/pull/283
- [x] Ping @prigoyal on discord after done
- [x] Rename https://github.com/facebookresearch/vissl/pull/283 to reflect what's it about - Merge by **April 14** **HARD DEADLINE**
- [x] For the Phase 1, open and rebase PR https://github.com/facebookresearch/vissl/pull/221 *April 13* EOD **HARD DEADLINE**
- [x] Finish #16 (create PR, **merge** PR in MLH fork) (Wednesday **HARD DEADLINE** April 22). (address feedback, review round)
     - [x] Complete all steps by April 22 + get 1st round of review from @prigoyal by April 22. 
- [ ] Send a phase 2 (new) to upstream #15 and #16 to [facebookresearch/vissl](https://github.com/facebookresearch/vissl) (**HARD DEADLINE** April 22) 
    - this will not be merged yet
